amp: true
batch: -1
box: 7.5
cache: false
cls: 0.5
copy_paste: 0.0
cos_lr: false
degrees: 0.0
deterministic: true
device: 0
dfl: 1.5
dropout: 0.0
epochs: 50
exist_ok: false
fliplr: 0.5
flipud: 0.0
fraction: 1.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 1280
kobj: 2.0
label_smoothing: 0.0
lr0: 0.01
lrf: 0.01
mask_ratio: 4
mixup: 0.0
model: None
momentum: 0.937
mosaic: 1.0
name: Plant-NTA1T6
nbs: 64
optimizer: auto
overlap_mask: true
patience: 10000
perspective: 0.0
pose: 12.0
pretrained: true
profile: false
project: /home/gemini/mnt/d/GEMINI-App-Data-DEMO/Intermediate/2022/Subset/Davis/Cowpea/Training/T4/RGB
  Plant Detection
rect: false
resume: false
save: true
save_period: -1
scale: 0.5
seed: 0
shear: 0.0
single_cls: false
translate: 0.1
val: true
verbose: false
warmup_bias_lr: 0.1
warmup_epochs: 3.0
warmup_momentum: 0.8
weight_decay: 0.0005
workers: 4
